// Generated by the Supabase CLI from the staging project, which carries
// every migration in supabase/migrations. Regenerate after a schema change:
//   supabase gen types typescript --project-id <staging-ref> \
//     > src/integrations/supabase/types.ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      letters: {
        Row: {
          created_at: string
          id: string
          letter_content: string | null
          patient_id: string | null
          patient_name: string | null
          recording_id: string
          status: string
          template_id: string | null
          transcript: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          letter_content?: string | null
          patient_id?: string | null
          patient_name?: string | null
          recording_id: string
          status?: string
          template_id?: string | null
          transcript?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          letter_content?: string | null
          patient_id?: string | null
          patient_name?: string | null
          recording_id?: string
          status?: string
          template_id?: string | null
          transcript?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "letters_recording_id_fkey"
            columns: ["recording_id"]
            isOneToOne: false
            referencedRelation: "recordings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "letters_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "templates"
            referencedColumns: ["id"]
          },
        ]
      }
      processing_audit_log: {
        Row: {
          action: string
          actor_role: string | null
          actor_user_id: string
          created_at: string
          detail: Json | null
          id: string
          outcome: string
          resource: string | null
          resource_id: string | null
          user_id: string
        }
        Insert: {
          action: string
          actor_role?: string | null
          actor_user_id: string
          created_at?: string
          detail?: Json | null
          id?: string
          outcome?: string
          resource?: string | null
          resource_id?: string | null
          user_id: string
        }
        Update: {
          action?: string
          actor_role?: string | null
          actor_user_id?: string
          created_at?: string
          detail?: Json | null
          id?: string
          outcome?: string
          resource?: string | null
          resource_id?: string | null
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          audio_retention_days: number
          auto_send_enabled: boolean
          auto_send_recipients: string[]
          clinician_id: string | null
          created_at: string
          dictation_engine: string
          full_name: string | null
          hospital_organisation: string | null
          id: string
          inactivity_timeout_minutes: number
          letter_template: string | null
          role: string
          role_title: string | null
          skip_dictation_review: boolean
          stripe_customer_id: string | null
          transcript_retention_days: number
          updated_at: string
          user_id: string
        }
        Insert: {
          audio_retention_days?: number
          auto_send_enabled?: boolean
          auto_send_recipients?: string[]
          clinician_id?: string | null
          created_at?: string
          dictation_engine?: string
          full_name?: string | null
          hospital_organisation?: string | null
          id?: string
          inactivity_timeout_minutes?: number
          letter_template?: string | null
          role?: string
          role_title?: string | null
          skip_dictation_review?: boolean
          stripe_customer_id?: string | null
          transcript_retention_days?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          audio_retention_days?: number
          auto_send_enabled?: boolean
          auto_send_recipients?: string[]
          clinician_id?: string | null
          created_at?: string
          dictation_engine?: string
          full_name?: string | null
          hospital_organisation?: string | null
          id?: string
          inactivity_timeout_minutes?: number
          letter_template?: string | null
          role?: string
          role_title?: string | null
          skip_dictation_review?: boolean
          stripe_customer_id?: string | null
          transcript_retention_days?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      recordings: {
        Row: {
          audio_path: string
          audio_purged_at: string | null
          created_at: string
          duration_seconds: number | null
          id: string
          mode: string | null
          patient_id: string | null
          patient_name: string | null
          status: string
          template_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          audio_path: string
          audio_purged_at?: string | null
          created_at?: string
          duration_seconds?: number | null
          id?: string
          mode?: string | null
          patient_id?: string | null
          patient_name?: string | null
          status?: string
          template_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          audio_path?: string
          audio_purged_at?: string | null
          created_at?: string
          duration_seconds?: number | null
          id?: string
          mode?: string | null
          patient_id?: string | null
          patient_name?: string | null
          status?: string
          template_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recordings_template_id_fkey"
            columns: ["template_id"]
            isOneToOne: false
            referencedRelation: "templates"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          created_at: string
          current_period_end: string | null
          id: string
          letters_per_month: number
          plan: string
          quota_exempt: boolean
          status: string
          stripe_subscription_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          current_period_end?: string | null
          id?: string
          letters_per_month?: number
          plan?: string
          quota_exempt?: boolean
          status?: string
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          current_period_end?: string | null
          id?: string
          letters_per_month?: number
          plan?: string
          quota_exempt?: boolean
          status?: string
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      templates: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_default: boolean
          is_preset: boolean
          mode: string
          name: string
          prompt: string
          sort_order: number
          updated_at: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_default?: boolean
          is_preset?: boolean
          mode?: string
          name: string
          prompt: string
          sort_order?: number
          updated_at?: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_default?: boolean
          is_preset?: boolean
          mode?: string
          name?: string
          prompt?: string
          sort_order?: number
          updated_at?: string
          user_id?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      letter_usage_current_month: {
        Row: {
          letters_this_month: number | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      audit_detail_is_clean: { Args: { d: Json }; Returns: boolean }
      gdpr_erase_patient: {
        Args: {
          p_expected_count?: number
          p_patient_id?: string
          p_patient_name?: string
        }
        Returns: Json
      }
      gdpr_erase_user: { Args: never; Returns: Json }
      gdpr_export_patient: {
        Args: { p_patient_id?: string; p_patient_name?: string }
        Returns: Json
      }
      gdpr_export_user: { Args: never; Returns: Json }
      gdpr_find_patient_records: {
        Args: { p_patient_id?: string; p_patient_name?: string }
        Returns: {
          created_at: string
          has_audio: boolean
          has_letter: boolean
          letter_id: string
          patient_id: string
          patient_name: string
          recording_id: string
          status: string
          transcript_chars: number
        }[]
      }
      gdpr_norm_patient_id: { Args: { v: string }; Returns: string }
      gdpr_purge_expired_audio: { Args: never; Returns: number }
      get_my_clinician_id: { Args: never; Returns: string }
      log_audit_event: {
        Args: {
          p_action: string
          p_detail?: Json
          p_outcome?: string
          p_resource?: string
          p_resource_id?: string
          p_subject_id?: string
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
